export const simpleATSAnalysis = (cv) => {
  const commonATSKeywords = [
    // Habilidades transversales (Soft Skills)
    'liderazgo',
    'trabajo en equipo',
    'resolución de problemas',
    'comunicación',
    'adaptabilidad',
    'pensamiento crítico',
    'gestión del tiempo',
    'creatividad',
    'toma de decisiones',
    'organización',
    'negociación',
    'gestión del cambio',
    'orientación a resultados',
    'iniciativa',
    'empatía',
    'pensamiento estratégico',
    'atención al detalle',
    'multitarea',
    'liderazgo situacional',
    'coaching',
    'mentoring',
    'planificación',
    'gestión de conflictos',
    'networking',
    'gestión de stakeholders',

    // Lenguajes y marcos de programación
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'C#',
    'C++',
    'Ruby',
    'PHP',
    'Go',
    'Rust',
    'Kotlin',
    'Swift',
    'Scala',
    'Perl',
    'React',
    'Angular',
    'Vue.js',
    'Svelte',
    'Next.js',
    'Nuxt.js',
    'Node.js',
    'Express',
    'Django',
    'Flask',
    'Spring Boot',
    'Ruby on Rails',
    '.NET',
    'ASP.NET',
    'Laravel',
    'Symfony',

    // Bases de datos y Big Data
    'SQL',
    'MySQL',
    'PostgreSQL',
    'Oracle',
    'SQL Server',
    'MongoDB',
    'Redis',
    'Cassandra',
    'Elasticsearch',
    'Hadoop',
    'Spark',
    'Kafka',

    // DevOps y Cloud
    'AWS',
    'Azure',
    'Google Cloud',
    'Docker',
    'Kubernetes',
    'Terraform',
    'Ansible',
    'Jenkins',
    'GitLab CI/CD',
    'CircleCI',
    'Travis CI',
    'CI/CD',
    'monitorización',
    'Prometheus',
    'Grafana',
    'ELK Stack',

    // Diseño y UX/UI
    'Adobe Photoshop',
    'Illustrator',
    'Figma',
    'Sketch',
    'Adobe XD',
    'InVision',
    'Principle',
    'Zeplin',
    'usabilidad',
    'wireframing',
    'prototipado',
    'investigación de usuarios',
    'arquitectura de la información',

    // Marketing y Ventas
    'SEO',
    'SEM',
    'Google Analytics',
    'Google Ads',
    'Facebook Ads',
    'content marketing',
    'email marketing',
    'CRM',
    'Salesforce',
    'HubSpot',
    'inbound marketing',
    'outbound marketing',
    'Lead Generation',
    'Account Management',
    'pitching',
    'retención de clientes',

    // Finanzas y contabilidad
    'contabilidad',
    'auditoría',
    'análisis financiero',
    'gestión de riesgos',
    'ERP',
    'SAP',
    'QuickBooks',
    'Xero',
    'SAP FI/CO',
    'Oracle Financials',
    'tesorería',
    'presupuestos',
    'forecasting',
    'control de gestión',

    // RRHH y operaciones
    'reclutamiento',
    'selección de personal',
    'Onboarding',
    'formación',
    'desarrollo de talento',
    'compensaciones y beneficios',
    'relaciones laborales',
    'evaluación del desempeño',
    'procesos de RRHH',
    'lean management',
    'six sigma',
    'kaizen',
    'gestión de la calidad',
    'logística',
    'supply chain',

    // Ciencia de Datos e IA
    'Machine Learning',
    'Deep Learning',
    'Data Science',
    'Data Analysis',
    'Pandas',
    'NumPy',
    'scikit-learn',
    'TensorFlow',
    'Keras',
    'PyTorch',
    'R',
    'MATLAB',
    'visualización de datos',
    'Power BI',
    'Tableau',
    'big data',
    'ETL',
    'data engineering',

    // Infraestructura y Redes
    'Cisco',
    'routing',
    'switching',
    'firewall',
    'VPN',
    'TCP/IP',
    'network security',
    'virtualización',
    'VMware',
    'Hyper-V',

    // Legal y cumplimiento
    'GDPR',
    'compliance',
    'derecho laboral',
    'derecho mercantil',
    'due diligence',
    'propiedad intelectual',
    'contratos',

    // Otros
    'gestión de proyectos',
    'PMP',
    'Prince2',
    'SCRUM',
    'Kanban',
    'Agile',
    'SAFE',
    'SAFe',
    'ITIL',
    'ISO 9001',
    'ISO 27001',
    'reporting',
    'KPIs',
    'benchmarking'
  ]

  const foundKeywords = cv.hablidades.filter((h) =>
    commonATSKeywords.includes(h.toLowerCase())
  )
  const score = Math.min(
    (foundKeywords.length / commonATSKeywords.length) * 50 +
      cv.experiencia.length * 10 +
      cv.educacion.length * 10,
    100
  )

  return {
    score,
    suggestions:
      foundKeywords.length < 3
        ? ['Agrega mas palabras clave de la industria']
        : [],
    keywordsMatch: foundKeywords
  }
}
